config/routes.rb
NoCms::Admin::Pages::Engine.routes.draw do
  
  root to: "pages#index"

  resources :pages do |pages|
    member do
      patch :preview
    end
  end
end

app/controllers/no_cms/admin/pages/application_controller.rb
module NoCms
  module Admin
    module Pages
      class ApplicationController < NoCms::Admin::ApplicationController
      end
    end
  end
end

app/controllers/no_cms/admin/pages/pages_controller.rb
require_dependency "no_cms/admin/pages/application_controller"

module NoCms::Admin::Pages
  class PagesController < ApplicationController

    before_filter :load_menu_section
    before_filter :load_page, only: [:preview, :edit, :update, :destroy]
    before_filter :load_roots, only: [:index, :new, :edit]


    def new
      @page = NoCms::Pages::Page.new
    end

    def create
      @page = NoCms::Pages::Page.new page_params
      if @page.save
        @nocms_logger.info(I18n.t('.no_cms.admin.pages.pages.create.success', title: @page.path), true)
        redirect_after_save
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.pages.pages.create.error', title: @page.path))
        load_roots
        render :new
      end
    end

    def edit
      @nocms_logger.add_message :pages, I18n.t('.no_cms.admin.pages.pages.edit.log_messages', title: @page.path)
      load_block_templates
    end

    def update
      if @page.update_attributes page_params
        @nocms_logger.info(I18n.t('.no_cms.admin.pages.pages.update.success', title: @page.path), true)
        redirect_after_save
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.pages.pages.update.error', title: @page.path))
        load_roots
        load_block_templates
        render :edit
      end
    end

    def destroy
      if @page.destroy
        @nocms_logger.info(I18n.t('.no_cms.admin.pages.pages.destroy.success', title: @page.path), true)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.pages.pages.destroy.error', title: @page.path), true)
      end
      redirect_to pages_path
    end

    def preview
      @page.assign_attributes page_params
      @blocks = @page.blocks.select{|b| b.draft == '0'}
      render template: 'no_cms/pages/pages/show', layout: 'application'
    end

    private

    def load_block_templates
      NoCms::Blocks.block_layouts.each do |name, _|
        @page.blocks.build layout: name, no_cms_admin_template: true
      end
    end

    def load_menu_section
      @current_section = 'pages'
    end

    def load_page
      @page = NoCms::Pages::Page.find(params[:id])
    end

    def load_roots
      @roots = NoCms::Pages::Page.roots
    end

    def page_params
      page_params = params.require(:page).permit(:title, :template, :slug, :body, :parent_id, :draft, :css_class, :css_id, :cache_enabled, :layout)
      page_params.merge!(blocks_attributes: params[:page][:blocks_attributes]) unless params[:page][:blocks_attributes].blank?
      page_params
    end

    def redirect_after_save
      if params[:submit_and_hide]
        redirect_to pages_path
      elsif params[:submit_and_new]
        redirect_to new_page_path
      else params[:submit]
        redirect_to edit_page_path(@page)
      end

    end

  end
end

app/helpers/no_cms/admin/pages/application_helper.rb
module NoCms
  module Admin
    module Pages
      module ApplicationHelper
      end
    end
  end
end

app/helpers/no_cms/admin/pages/pages_helper.rb
module NoCms::Admin::Pages
  module PagesHelper

    def page_listing_item_classes page, current_page
      classes = []
      classes << 'current' if current_page == page
      classes << 'oculto' if page.draft
      classes
    end

    def block_form_classes block
      classes = []
      classes << 'oculto' if block.draft
      classes << 'new' if block.new_record?
      classes
    end

    def block_form_id block
      block.new_record? ?
      "new_content_block_#{block.layout}" :
      "content_block_#{block.id}"
    end

  end
end

app/views/no_cms/admin/pages/blocks/_default.html.erb
<div class="row">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="row">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>

app/views/no_cms/admin/pages/blocks/_form.html.erb
<div class="b-title row">
  <a href="#" class="btn-square ico-collapse-v js-collapse-block" title="Expand /Collapse"></a>

  <%= f.select :layout, NoCms::Blocks.block_layouts.map{|name, layout| [
      I18n.t("no_cms.pages.blocks.layouts.#{name}"),
      name,
      'data-nest-levels' => layout[:nest_levels].nil? ? nil : layout[:nest_levels].to_json
    ]},
    {}, class: 'block_layout_selector' %>

  <div class="mo">
    <a href="" class="ico-mini-delete"><%= t('.remove') %></a>
    <a href="" class="ico-mini-move-up"><%= t('.move_up') %></a>
    <a href="" class="ico-mini-move-down"><%= t('.move_down') %></a>
    <a href="" class="ico-mini-show-hide"><%= t('.hide') %></a>
  </div>
</div>
<div class='layout_fields'>
  <%= render "no_cms/admin/pages/blocks/#{f.object.template}" , f: f %>
  <%= render 'no_cms/admin/pages/blocks/nested_index', f: f if f.object.layout_config[:allow_nested_blocks] %>
</div>

<%= f.hidden_field :position, class: 'position' %>
<%= f.hidden_field :draft,  class: 'draft', value: f.object.draft ? '1' : '0' %>
<%= f.hidden_field :_destroy,  class: 'destroy', value: f.object.no_cms_admin_template ? '1' : '0' %>

app/views/no_cms/admin/pages/blocks/_index.html.erb
<div class="row has-children content_blocks_placeholder">
  <div class="tool-bar-blocks">
    <a href="#" class="btn-square ico-collapse-v js-collapse-all-children-blocks" title="Collapse all blocks"></a>
    <label><%= t('.title') %></label>
    <%= link_to t('.new_block'), '#', class: 'new_content_block btn _m0' %>
  </div>


  <%= f.fields_for :blocks, f.object.blocks.reject(&:parent).sort_by{|b| b.new_record? ? Float::INFINITY : b.position} do |f_block| %>

    <div class="block row <%= block_form_classes(f_block.object).join(" ")%>" id="<%= block_form_id(f_block.object) %>">
      <%= render 'no_cms/admin/pages/blocks/form', f: f_block %>
    </div>
  <% end %>
</div>

app/views/no_cms/admin/pages/blocks/_nested_index.html.erb
<div class="row">
  <div class="row has-children content_blocks_placeholder">
    <div class="tool-bar-blocks">
      <a href="#" class="btn-square ico-collapse-v js-collapse-all-children-blocks" title="Collapse all blocks"></a>
      <label><%= t('.title') %></label>
      <%= link_to t('.new_block'), '#', class: 'new_content_block btn _m0' %>
    </div>


    <%= f.fields_for :children, f.object.children.sort_by(&:position) do |f_child| %>

      <div class="block row <%= block_form_classes(f_child.object).join(" ")%>" id="<%= block_form_id(f_child.object) %>">
        <%= render 'no_cms/admin/pages/blocks/form', f: f_child %>
      </div>
    <% end %>
  </div>
</div>

app/views/no_cms/admin/pages/pages/_content_fields.html.erb
<div id="content_fields">
  <div class="row">
    <%= f.label :parent_id %>
    <%= f.select :parent_id, NoCms::Pages::Page.with_translations.map{|p| [p.path, p.id]}, include_blank: t('.choose_page') %>
  </div>
  <div class="row">
    <%= f.label :layout %>
    <%= f.select :layout, NoCms::Pages::Page.layouts.map{|t| [I18n.t(".no_cms.admin.pages.pages.layouts.#{t}"), t] } %>
  </div>
  <div class="row">
    <%= f.label :template %>
    <%= f.select :template, NoCms::Pages::Page.templates.map{|t| [I18n.t(".no_cms.admin.pages.pages.templates.#{t}"), t] } %>
  </div>
  <div class="row">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="row">

    <%= f.label_with_tooltip :slug, { tooltip: t('.slug_tooltip')} %>

    <%= f.object.parent.path unless f.object.parent.nil? %>
    <%= f.text_field :slug %>
  </div>

  <% if NoCms::Pages.cache_enabled %>
    <div class="row">
      <%= f.label_with_tooltip :cache_enabled, { tooltip: t('.cache_enabled_tooltip')} %>
      <%= f.check_box :cache_enabled %>
    </div>
  <% end %>

  <div class="row">

    <%= f.label_with_tooltip :css_class, t('.css_settings'), { tooltip: t('.css_settings_tooltip')} %>

    <%= f.text_field :css_class, class: 'half', placeholder: t('activerecord.attributes.no_cms/pages/page.css_class') %>
    <%= f.text_field :css_id, class: 'half', placeholder: t('activerecord.attributes.no_cms/pages/page.css_id') %>
  </div>

  <% if NoCms::Pages.use_body %>
    <div class="row">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>
  <% end %>
</div>

app/views/no_cms/admin/pages/pages/_page_listing.html.erb
<ul>
  <%= yield %>
</ul>

app/views/no_cms/admin/pages/pages/_page_listing_item.html.erb
<% current ||= nil %>
<li <%= raw "class='#{page_listing_item_classes(page, current).join(' ')}'"%>>
  <%= link_to page.title, edit_page_path(page)%>
  <div class="mo">
    <%= button_to '', page_path(page), method: :delete, class: "ico-mini-delete", title: t('.destroy') %>
    <%= button_to page_path(page), method: :put, class: "ico-mini-show-hide", title: (page.draft ? t('.show') : t('.hide')) do %>
      <% fields_for page do |f| %>
        <%= f.hidden_field :draft, value: (page.draft ? "0" : "1") %>
      <% end %>
    <% end %>
  </div>
  <%= render partial: 'page_listing_item', collection: page.children, as: 'page', layout: 'page_listing', locals: { current: current } unless page.children.blank? %>
</li>

app/views/no_cms/admin/pages/pages/_toolbar.html.erb
<%= f.submit t('.submit'), name: :submit, class: "btn right" %>
<%= f.submit t('.submit_and_new'), name: 'submit_and_new', class: "btn right" %>
<%= f.submit t('.submit_and_hide'), name: 'submit_and_hide', class: "btn right" %>

app/views/no_cms/admin/pages/pages/_toolbar_right.html.erb
<%= f.submit t('.submit'), name: :submit, class: "btn right" %>
<%= f.submit t('.submit_and_new'), name: 'submit_and_new', class: "btn right" %>
<%= f.submit t('.submit_and_hide'), name: 'submit_and_hide', class: "btn right" %>
<%= link_to t('.preview'), preview_page_path(@page), 'data-preview' => true, class: "preview btn right" unless @page.new_record? %>
<% # We must check that nocms-pages routes are mounted. Otherwise it will get a 404 error %>
<%= link_to t('.visit'), @page.path, target: '_blank', class: "preview btn right" if defined?(no_cms_pages) && !@page.new_record?  %>

app/views/no_cms/admin/pages/pages/edit.html.erb
<% content_for :ready_js do %>
  NoCMS.Admin.BlockHandler();
<% end %>

<% content_for :second_menu do %>
  <%= render partial: 'page_listing_item', collection: @roots, as: 'page', layout: 'page_listing', locals: { current: @page } unless @roots.blank? %>
<% end %>


<%= no_cms_admin_form_for @page do |f| %>
  <%= render partial: 'no_cms/admin/shared/toolbar', locals: { f: f } %>
  <div class="content">
    <%= render 'no_cms/admin/shared/log_messages' %>
    <%= render 'content_fields', f: f %>
    <%= render 'no_cms/admin/pages/blocks/index', f: f %>
  </div>
<% end %>

app/views/no_cms/admin/pages/pages/index.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'page_listing_item', collection: @roots, as: 'page', layout: 'page_listing' unless @roots.blank? %>
<% end %>

<div class="content">
  <%= render 'no_cms/admin/shared/log_messages' %>
</div>

app/views/no_cms/admin/pages/pages/new.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'page_listing_item', collection: @roots, as: 'page', layout: 'page_listing', locals: { current: @page } unless @roots.blank? %>
<% end %>

<%= no_cms_admin_form_for @page do |f| %>
  <%= render partial: 'no_cms/admin/shared/toolbar', locals: { f: f } %>
  <div class="content">
    <%= render 'no_cms/admin/shared/log_messages' %>
    <%= render 'content_fields', f: f %>
  </div>

<% end %>